[package]
name = "bmap"
version = "0.1.0"
authors = ["bluss"]

[dependencies.arrayvec]
#path = "../arrayvec"
version = "0.3.4"

[dev-dependencies]
rand = "*"
itertools = "0.3.11"

[dependencies.odds]
version = "0.2.1"

[profile.bench]
#lto = false
#debug = true
