[package]
name = "bmap"
version = "0.1.0"
authors = ["bluss"]

[dependencies.arrayvec]
#path = "../arrayvec"
version = "0.3.4"

[dev-dependencies]
rand = "*"

[profile.bench]
#lto = false
#debug = true
